# Site
name: 'Sunrise Travel'
description: 'Travel & Real Estate'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/sunrise-travel'
avatar: 'assets/images/sal.jpg'
email: 'info@sunrisetravel.ge'

include: ["_pages"]
permalink: pretty



# Plugins
plugins: 
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-postfiles
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
